kubelet:
  image: gcr.io/google_containers/kubelet:v1.2.5
  privileged: true
  net: "host"
  pid: "host"
  command: >
    /kubelet
    --enable-debugging-handlers=true
    --config=/etc/kubernetes/manifests
    --allow-privileged=true
    --v=2
    --root-dir=/var/lib/kubelet
    --port=10250
    --hairpin-mode="promiscuous-bridge"
    2>&1
  volumes:
    - /var/run:/var/run
    - /srv/kubernetes:/srv/kubernetes
    - /etc/kubernetes/manifests:/etc/kubernetes/manifests

kube-proxy:
  image: gcr.io/google_containers/kube-proxy:v1.2.5
  privileged: true
  net: "host"
  pid: "host"
  command: >
    kube-proxy
    --master=http://${HOST_IP}:${K8S_APISERVER_PORT}
    --v=5
    2>&1
  volumes:
    - /var/run:/var/run
    - /var/log:/var/log
    - /usr/share/ca-certificates:/etc/ssl/certs
